name: Reservaki CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: mvn clean test

      - name: Generate Test Reports
        if: always()
        run: mvn surefire-report:report

      - name: Store Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/site/
            target/surefire-reports/
          retention-days: 7

  package:
    name: Package Application
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR
        run: mvn -B package -DskipTests

      - name: Store JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 7